name: Build and Push Docker API to GCR

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"
          project_id: your-projectid
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        run: |
          docker build -f Dockerfile-api -t gcr.io/your-projectid/your-image-name:$GITHUB_SHA .

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/your-projectid/your-image-name:$GITHUB_SHA

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - id: "deploy"
        run: |-
          gcloud run deploy your-image-name \
          --image=gcr.io/your-projectid/your-image-name:${{ github.sha }} \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated
